global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-service:8081']
        labels:
          application: 'auth-service'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
